call pathogen#infect('bundle/{}')
au BufRead,BufNewFile *.sls setfiletype yaml

set laststatus=2
set modeline

"tab behaviour
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent

filetype on
filetype plugin on "for vimwiki
filetype indent plugin on
syntax on "for vimwiki

"yank to OS clipboard
set clipboard=unnamedplus

"search
set hlsearch

"user-defined commands
command VWT VimwikiTOC

"invisibles
set list listchars=tab:>-

"enable fzf plugin
set rtp+=~/.fzf

"mappings
map <C-o> :NERDTreeToggle<CR>
map <C-k> :VimwikiTOC<CR>

"emmet
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_leader_key=','
